### ISSUE TITLE
Security Concept and Encryption

### ISSUE THREAD

**Issue by cb0s** [TelestionTeam/telestion#15]
In order to create a useful software we need to provide security. To ensure secure connections we will have to talk about various encryption methods and have to decide which one we will use.

Apart from this we have to create a "security protocol" how people that use or analyse or software should report bugs and/or security vulnerabilities.

**TODO:**

- [ ] MAVLink-Encryption
- [ ] Security Protocol
- [ ] Local TCP Connection Security

*If there are more places where we need a security protocol please add them in a later edit.*

**Comment by jvpichowski** [comment]
Since there is no real use-case yet and we don't see any proposal it is time to close this. If you have any additions feel free to reopen again.
