### ISSUE TITLE
Bad-Packet Correction Algorithms

### ISSUE THREAD

**Issue by cb0s** [TelestionTeam/telestion#23]
In some cases (e.g. MAV-Link) you only get basic checksums to identify bad packets. This however means that at the moment we just save those packets without doing anything with them.

With bit checking there might be possibilities to transform those to valid packets. (Example: Byte: 1000 1011 though the bounds are 0111 1111 so you know 0000 1011 might be a valid packet. There might also be other algorithms e.g. machine learning etc.)

**Comment by jvpichowski** [comment]
So we put this on hold until there is a real concept.
