### ISSUE TITLE
Unique JsonMessage.name()

### ISSUE THREAD

**Issue by jvpichowski** [TelestionTeam/telestion#30]
In a system only unique message names should be exist. This is could be enforced with an assertion verticle. For reference hav a look at the name checks in HistoryCache.

**Comment by cb0s** [comment]
Still relevant or already closed in #104

**Comment by jvpichowski** [comment]
I think for now it is fine. If we run into trouble because somebody introduces a variable called `className` in its message, we will see how to solve it.
